import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const poppins = Poppins({
  subsets: ["latin"], // Choose your subsets
  weight: ["400", "500", "700"], // Add weights as needed
  variable: "--font-poppins", // Optional: CSS variable for font
});

export const metadata: Metadata = {
  title: "My Work Clock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="min-h-screen flex flex-col">
          <header className="bg-background border-b">
            <div className="container mx-auto px-4">
              <nav className="flex items-center justify-between h-16">
                <Link href="/" className="text-lg font-semibold">
                  Employee Dashboard
                </Link>
                <div className="flex items-center space-x-4">
                  <Button variant={"ghost"} asChild>
                    <Link href="/">Dashboard</Link>
                  </Button>
                  <Button variant={"ghost"} asChild>
                    <Link href="/settings">Settings</Link>
                  </Button>
                </div>
              </nav>
            </div>
          </header>
          <main className="flex-grow container mx-auto px-4 py-8">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
